name: Test Workflow

on:
  repository_dispatch:
    types: [run_test_workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
      - name: Run a one-line script
        run: echo ${{ github.event.client_payload.release_label }}
        
      - name: Get Latest Jellyfin-vue
        id: latest-vue
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: jellyfin
          repo: jellyfin-vue
          excludes: prerelease, draft
        
      - name: Get Latest Jellyfin-vue PreRelease
        id: latest-vue-prereleasee
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: jellyfin
          repo: jellyfin-vue
          excludes: release, draft
          
      - name: Clone jellyfin-vue
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-vue'
          platform: 'github'
          path: 'jellyfin-vue'
          ref: ${{ steps.latest-vue.outputs.release }}
          
      - name: Clone jellyfin-vue PreRelease
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-vue'
          platform: 'github'
          path: 'jellyfin-vue-prerelease'
          ref: ${{ steps.latest-vue-prereleasee.outputs.release }}
          
      - run: ls
        
      - name: Set Release Label
        uses: haya14busa/action-cond@v1
        id: label
        with:
          cond: ${{ github.event.client_payload.release_label != 0 }}
          if_true: ${{ github.event.client_payload.release_label }}
          if_false: ${{ steps.date.outputs.date }}
      
      - name: Print Final Label
        run: echo ${{ steps.label.outputs.value }}
        
      - name: Print Release Info
        run: |
          echo ${{ github.event.client_payload.data.vueRelease.name }}
          echo ${{ github.event.client_payload.data.vuePreRelease.name }}
